### ISSUE TITLE
Post-Mortem

### ISSUE THREAD

**Issue by DVBrown93** [fs-tech-degs/capstone-DVBrown93#85]
> **Feedback**

**General Notes**
* I haven't received any notes from this Final Milestone. However, the previous Milestones the feed back I received:
  * Update main readme
    * Instructions on readme on how to run projects
  * Remove directory or label as src
  * Add sample .env

**Action Items**
* [x] Update main readme
* [x] Instructions on readme on how to run projects
* [x] Remove directory or label as src
* [x] Add sample .env

**Follow up**
All actions are completed waiting for feedback on the final milestone.

**Team Members Involved**

| Team Member        |
| ------------- |
| Chapman | 
| Brandon |

**Comment by reactivepixel** [comment]
Very good work knocking out this feedback. Closing.
